# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your Python package with all the requirements
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
